paths:
  /testSuites/{testSuiteId}/validationTags:
    post:                 
      tags:            
        - ValidationTag
      summary: Creates a new validation tag linked to a test suite
      produces:
        - application/json
      parameters:    
        - name: testSuiteId
          in: path
          description: ID of the test suite that the created validation tag will be linked to
          required: true
          schema:
            type: string
      requestBody:
        description: 
        required: true
        content:
          application/json:
            schema:
              $ref: '#/definitions/validationTag'
     
      responses:      
        201:
          description: Validation tag on a test suite is created successfully
          content:
            application/json:
              schema:
                $ref: '#/definitions/validationTagOnTestSuite'
        400:
          description: Path parameter `testSuiteId` is not a valid ID
          content:
            application/json:
              schema:
                $ref: '#/definitions/validationTagErrorResponse'

  /testSuites/{testSuiteId}/testCases/{testCaseId}/validationTags:
    post:                 
      tags:            
        - ValidationTag
      summary: Creates a new validation tag linked to a test case
      produces:
        - application/json
      parameters:    
        - name: testSuiteId
          in: path
          description: ID of the test suite that `testCaseId` belongs to
          required: true
          schema:
            type: string
        - name: testCaseId
          in: path
          description: ID of the test case that the created validation tag will be linked to
          required: true
          schema:
            type: string
      requestBody:
        description: 
        required: true
        content:
          application/json:
            schema:
              $ref: '#/definitions/validationTag'
     
      responses:      
        201:
          description: Validation tag on a test case is created successfully
          content:
            application/json:
              schema:
                $ref: '#/definitions/validationTagOnTestCase'
        400:
          description: 1. Path parameter `testSuiteId` is not a valid ID<br>2. Path parameter `testCaseId` is not a valid ID<br>3. `testCaseId` does not belong to `testSuiteId`
          content:
            application/json:
              schema:
                $ref: '#/definitions/validationTagErrorResponse'

  /validationTags/{validationTagId}:
    get:                 
      tags:            
        - ValidationTag
      summary: Fetches a validation tag by its ID
      produces:
        - application/json
      parameters:    
        - name: validationTagId
          in: path
          description: ID of the validation tag to be fetched
          required: true
          schema:
            type: string
     
      responses:      
        200:
          description: Validation tag with `validationTagId` is fetched successfully
          content:
            application/json:
              schema:
                $ref: '#/definitions/validationTagGetResponse'
        404:
          description: Validation tag with `validationTagId` does not exist
          content:
            application/json:
              schema:
                $ref: '#/definitions/validationTagErrorResponse'
  

definitions: # Schema defination for request body
  validationTag:
    type: object
    properties:
      isSuccessful:
        type: boolean
        example: true
      metaData:
        type: object

  validationTagOnTestSuite:
    type: object
    properties:
      id: 
        type: string
        example: 507f1f77bcf86cd799439011
      isSuccessful:
        type: boolean
        example: true
      metaData:
        type: object
      parent: 
        type: object
        properties:
          testSuite:
            type: object
            properties:
              id:
                type: string
                example: 507f1f77bcf86cd799439011
                
  validationTagOnTestCase:
    type: object
    properties:
      id: 
        type: string
        example: 507f1f77bcf86cd799439011
      isSuccessful:
        type: boolean
        example: true
      metaData:
        type: object
      parent: 
        type: object
        properties:
          testSuite:
            type: object
            properties:
              id:
                type: string
                example: 507f1f77bcf86cd799439011
          testCase:
            type: object
            properties:
              id:
                type: string
                example: 50879873145dfbqe4f5f4f5f

  validationTagGetResponse:
    type: object
    properties:
      id: 
        type: string
        example: 507f1f77bcf86cd799439011
      isSuccessful:
        type: boolean
        example: true
      metaData:
        type: object
      parent: 
        type: object
        properties:
          testSuite:
            type: object
            properties:
              id:
                type: string
                example: 507f1f77bcf86cd799439011
          testCase:
            type: object
            properties:
              id:
                type: string
                example: 50879873145dfbqe4f5f4f5f
      validationPoints:
        type: array
        items:
          $ref: '#/definitions/validationPointAsChild'


  validationTagErrorResponse:
    type: object
    properties:
      message:
        type: string
        example: error message
  
  
  validationPointAsChild:
    type: object
    properties:
      id: 
        type: string
        example: 507f1f77bcf86cd799439011
      type: 
        type: string
        example: "DUT"
      metaData: 
        type: object
      # parent:
      #   type: object
      #   properties:
      #     validationTag:
      #       type: object
      #       properties:
      #         id:
      #           type: string
      #           example: 1321fdsafdsafdsafdsafdsa
      #     testCase:
      #       type: object
      #       properties:
      #         id:
      #           type: string
      #           example: 121qfvasdfasdfasdfasdf
      #     testSuite:
      #       type: object
      #       properties:
      #         id:
      #           type: string
      #           example: 2225659qafksj6556adfasdf
      body:
        type: object
      
      