paths:
  /TestSuites/{id}:
    get:                 
      tags:            
        - TestSuite
      summary: get testsuite by id
      produces:
        - application/json
      parameters:    
        - name: id
          in: path
          description: ID of the test suite 
          required: true
          schema:
            type: string
      # requestBody:
      #   description: 
      #   required: true
      #   content:
      #     application/json:
      #       schema:
      #         $ref: '#/definitions/TestSuiteId'
     
      responses:      
        200:
          description: testsuite with given id is found & get it successfully
          content:
            application/json:
              schema:
                $ref: '#/definitions/TestSuite'
        400:
          description: Path parameter `id` is not a valid ID
          content:
            application/json:
              schema:
                $ref: '#/definitions/TestSuiteErrorResponse'
  
  /TestSuites/:
    get:                 
      tags:            
        - TestSuite
      summary: get all test suites
      produces:
        - application/json
      responses:      
        200:
          description: return all test suites  successfully
          content:
            application/json:
              schema:
                $ref: '#/definitions/TestSuites'
        400:
          description: Error at database connection 
          content:
            application/json:
              schema:
                $ref: '#/definitions/TestSuiteErrorResponse'
  /TestSuites/create:
    post:                 
      tags:            
        - TestSuite
      summary: add testsuite to the database 
      produces:
        - application/json
      requestBody:
        description: 
        required: true
        content:
          application/json:
            schema:
              $ref: '#/definitions/TestSuite'
     
      responses:      
        201:
          description: testsuite is created  successfully
          content:
            application/json:
              schema:
                $ref: '#/definitions/TestSuite'
        400:
          description: Error 
          content:
            application/json:
              schema:
                $ref: '#/definitions/TestSuiteErrorResponse'

definitions: # Schema defination for request body
  TestSuite:
    type: object
    properties:
      isSuccessful:
        type: boolean
        example: true
      metaData:
        type: object

  TestSuites:
    type: objects
    properties:
      id: 
        type: string
        example: 507f1f77bcf86cd799439011
      isSuccessful:
        type: boolean
        example: true
      metaData:
        type: object
  

  TestSuiteErrorResponse:
    type: object
    properties:
      message:
        type: string
        example: error message
                
  